version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 18.6.0
    commands:
      - echo "Node version 18.6.0 installed"
      - node -v
      - echo "Installing source NPM dependencies..."
      - npm ci

  build:
    commands:
      - echo "Building React app"
      - npm run build

artifacts:
  files:
    - '**/*'
  base-directory: build
